### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by SuperAZHE** [vtumi/remote-control-monitor-car-android#1]
请问一下，你是在android studio下开发这个的吗？

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有相应的服务端程序。

**Comment by vtumi** [comment]
是啊，不过要正常运行还需要有对应的服务端程序。

**Comment by SuperAZHE** [comment]
谢谢啦，我最近的课程设计和你的这个比较相关，正在学习使用AS，第一次用，有比较多的问题。

**Comment by vtumi** [comment]
https://github.com/vtumi/remote-control-monitor-car-server
这是服务端的程序，不过是用C写的。

**Comment by SuperAZHE** [comment]
谢谢，我们正在写自己的服务端程序，你的项目对我们的帮助很大
