### ISSUE TITLE
ImageButton的背景

### ISSUE THREAD

**Issue by SuperAZHE** [vtumi/remote-control-monitor-car-android#2]
你的铃铛还有红叉的背景是怎么去掉的，我试了android:background="#00000000"；可是还是把背景的留白在屏幕上显示了出来，实在没找到办法，所以又来请教了。

**Comment by vtumi** [comment]
#00000000
前面六位是色值，后面两位是透明度。
设置了按钮的透明度后，按钮图片还需要是背景透明的。

**Comment by SuperAZHE** [comment]
所以按钮图片的背景透明是在Ps等画图工具上操作的吗？我又试过将图片的背景删除（ppt上的方法），放入drawable之后，它的背景在屏幕上又回来了

**Comment by vtumi** [comment]
你使用源码中的图片有没有问题？

**Comment by SuperAZHE** [comment]
已经解决问题，源图片的背景没有被设置成透明；换了一张图片之后，效果已经实现，还是多谢帮助。
